In [1]:
import numpy as np
import pandas as pd


In [19]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score

df = pd.read_csv("student_iq_cgpa_package_200.csv")
df

IQ  CGPA  Package (LPA)  Year of Passing
0    139  7.38          16.86             2019
1    101  6.54          14.51             2024
2    113  5.96          15.19             2023
3    124  8.80          19.29             2019
4    120  9.08          22.44             2018
..   ...   ...            ...              ...
195  108  5.67          12.05             2020
196  131  6.52          14.54             2021
197  127  6.48          16.08             2023
198  130  8.78          22.09             2020
199  114  6.67          14.32             2022

[200 rows x 4 columns]

### KNN

In [21]:

X = df[["IQ", "CGPA", "Year of Passing"]]

y = pd.qcut(df["Package (LPA)"], q=3, labels=[0, 1, 2])

X_train, X_test, y_train, y_test = train_test_split(
    X, y, train_size=0.6, random_state=42, stratify=y
)

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

knn = KNeighborsClassifier(n_neighbors=7)
knn.fit(X_train_scaled, y_train)
knn_pred = knn.predict(X_test_scaled)

dt = DecisionTreeClassifier(max_depth=4, random_state=42)
dt.fit(X_train, y_train)
dt_pred = dt.predict(X_test)

nb = GaussianNB()
nb.fit(X_train, y_train)
nb_pred = nb.predict(X_test)

print("KNN Accuracy:", accuracy_score(y_test, knn_pred))
print("Decision Tree Accuracy:", accuracy_score(y_test, dt_pred))
print("Naive Bayes Accuracy:", accuracy_score(y_test, nb_pred))

print("KNN Confusion Matrix:\n", confusion_matrix(y_test, knn_pred))
print("Decision Tree Confusion Matrix:\n", confusion_matrix(y_test, dt_pred))
print("Naive Bayes Confusion Matrix:\n", confusion_matrix(y_test, nb_pred))


KNN Accuracy: 0.775
Decision Tree Accuracy: 0.75
Naive Bayes Accuracy: 0.775
KNN Confusion Matrix:
 [[23  4  0]
 [ 3 17  6]
 [ 1  4 22]]
Decision Tree Confusion Matrix:
 [[21  6  0]
 [ 2 17  7]
 [ 0  5 22]]
Naive Bayes Confusion Matrix:
 [[24  3  0]
 [ 2 16  8]
 [ 0  5 22]]
